### ISSUE TITLE
Wrong java code to load resource: ResourceBundle.getBundle("com/okta/commons/configcheck/ConfigurationValidator")

### ISSUE THREAD

**Issue by hli-git3** [okta/okta-commons-java#26] opened 2019-10-09 21:26 UTC
Issue: In class ConfigurationValidator for okta-config-check, the line to load resource bundle is wrong. It could be something like "com.okta.commons.configcheck.ConfigurationValidator". The "/" class name separator is forbidden by Oracle JDK version as early as 1.5. 

If you want to know more information about it, please take a look at the bug https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4986512

It causes NoClassDefFoundError when the class is being loaded in runtime:
 java.lang.NoClassDefFoundError: IllegalName: com/okta/commons/configcheck/ConfigurationValidator
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654) [rt.jar:1.8.0_201]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761) [rt.jar:1.8.0_201]

--original code --
public final class ConfigurationValidator {

    private static final Logger logger = LoggerFactory.getLogger(ConfigurationValidator.class);
    private static final ResourceBundle ERRORS = ResourceBundle.getBundle("com/okta/commons/configcheck/ConfigurationValidator");

**Comment by bdemers** [comment] 2020-06-16 16:45
Hi @hli-git3!

The resource bundle isn't loaded as a class, though it is loaded from the classpath.

In order to look into this more we would need to know which JVM you are using: OS, version, vendor, how is your classpath setup, and how you is your app packaged.

Also, it is worth noting that we found a problem with win JVM (Graal/Substrate), specifically when using native-image, there was a clash between the class name and the resource bundle name.  This has been fixed in the latest version `1.2.3`.  My first suggestion would be to update to that version.  

Details on the change: https://github.com/okta/okta-commons-java/commit/0c0db030bad1ae55c1d1620e4bd67866b5e17a82

Keep us posted!

**Comment by hlbraddock** [comment] 2020-06-26 20:30
Hello @bdemers!

Will you be publishing a new version to https://mvnrepository.com/artifact/com.okta.jwt/okta-jwt-verifier?  Will that version resolve the following:

We're currently using https://mvnrepository.com/artifact/com.okta.jwt/okta-jwt-verifier/0.4.0 which results in the following runtime warning:
```
Caused by: java.lang.NoClassDefFoundError: IllegalName: com/okta/commons/configcheck/ConfigurationValidator
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
        ... 153 more
```
This is running in JBoss WildFly Full 9.0.2.Final:
```
org.jboss.modules] (main) JBoss Modules version 1.4.3.Final
[org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
[org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Full 9.0.2.Final (WildFly Core 1.0.2.Final) starting
```

**Comment by bdemers** [comment] 2020-06-26 20:39
Ahh, I see, I'll get that started right now.
Can you also send me the output from `java -version` (I'll update the release notes with the JVMs that are known to cause this issue)

**Comment by bdemers** [comment] 2020-06-26 20:40
(NOTE: until it is released, you can just update that dependency in your Maven or Gradle configuration)

**Closed** 2020-06-29 19:37 UTC

**Comment by bdemers** [comment] 2020-06-30 00:26
@hlbraddock The latest release of the jwt verifier should have this fix, let us know if you run into any issues!

**Comment by hlbraddock** [comment] 2020-07-09 18:47
@bdemers I'm still seeing the same runtime warning `Caused by: java.lang.NoClassDefFoundError: IllegalName: com/okta/commons/configcheck/ConfigurationValidator`

Client pom.xml:
```
<version>1.1</version>
    <dependencies>
        <dependency>
            <groupId>com.okta.jwt</groupId>
            <artifactId>okta-jwt-verifier</artifactId>
            <version>${okta.jwt.version}</version>
        </dependency>

        <dependency>
            <groupId>com.okta.jwt</groupId>
            <artifactId>okta-jwt-verifier-impl</artifactId>
            <version>${okta.jwt.version}</version>
        </dependency>
         ....
         ....
         ....
         ....
    </dependencies>
```

Maven dependency tree:
```
--- maven-dependency-plugin:2.8:tree (default-cli) @ okta-client ---
[INFO] org.cru:okta-client:jar:1.1
[INFO] +- org.jboss.resteasy:resteasy-client:jar:3.0.8.Final:compile
[INFO] |  \- org.jboss.resteasy:resteasy-jaxrs:jar:3.0.8.Final:compile
[INFO] |     +- org.jboss.resteasy:jaxrs-api:jar:3.0.8.Final:compile
[INFO] |     +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar:1.0.1.Final:compile
[INFO] |     +- javax.activation:activation:jar:1.1:compile
[INFO] |     +- org.apache.httpcomponents:httpclient:jar:4.2.1:compile
[INFO] |     |  +- org.apache.httpcomponents:httpcore:jar:4.2.1:compile
[INFO] |     |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |     |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |     +- commons-io:commons-io:jar:2.1:compile
[INFO] |     \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] +- com.okta.jwt:okta-jwt-verifier:jar:0.4.0:compile
[INFO] +- com.okta.jwt:okta-jwt-verifier-impl:jar:0.4.0:compile
[INFO] |  +- com.okta.commons:okta-config-check:jar:1.1.0:compile
[INFO] |  +- com.okta.commons:okta-commons-lang:jar:1.1.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- io.jsonwebtoken:jjwt-api:jar:0.10.5:compile
[INFO] |  +- io.jsonwebtoken:jjwt-impl:jar:0.10.5:runtime
[INFO] |  +- io.jsonwebtoken:jjwt-jackson:jar:0.10.5:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.6:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.6:compile
[INFO] |  \- com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[INFO] +- com.squareup.okio:okio:jar:2.6.0:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.70:compile
[INFO] |  |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.3.61:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.3.61:compile
[INFO] \- org.jetbrains.kotlin:kotlin-test-junit:jar:1.3.61:test
[INFO]    +- org.jetbrains.kotlin:kotlin-test-annotations-common:jar:1.3.61:test
[INFO]    +- org.jetbrains.kotlin:kotlin-test:jar:1.3.61:test
[INFO]    |  \- org.jetbrains.kotlin:kotlin-test-common:jar:1.3.61:test
[INFO]    \- junit:junit:jar:4.12:test
[INFO]       \- org.hamcrest:hamcrest-core:jar:1.3:test
```

**Comment by bdemers** [comment] 2020-07-09 19:22
@hlbraddock make sure your `okta.jwt.version` property is set to `0.4.1`
